default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["RAILS_POSTGRESQL_EXAMPLE_DATABASE_USERNAME"] %>
  password: <%= ENV["RAILS_POSTGRESQL_EXAMPLE_DATABASE_PASSWORD"] %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_postgresql_example_development

test:
  <<: *default
  database: rails_postgresql_example_test

production:
  primary: &primary_production
    <<: *default
    database: rails_postgresql_example_production
    username: rails_postgresql_example
    password: <%= ENV["RAILS_POSTGRESQL_EXAMPLE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_postgresql_example_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_postgresql_example_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_postgresql_example_production_cable
    migrations_paths: db/cable_migrate
